// export const categories = [
  
//   { 
//     key: "airport", 
//     label: "Aeroporto", 
//     // image: require("../../../assets/airport.png") 
export const categories = [
  { key: 'cafe', label: 'Cafés' },
  { key: 'restaurant', label: 'Restaurantes' },
  { key: 'bakery', label: 'Docerias' },
  { key: 'bar', label: 'Bares' },
  { key: 'fast_food', label: 'Lanchonetes' },
  { key: 'buffet', label: 'Buffets' },
  { key: 'supermarket', label: 'Supermercados' },
  { key: 'clothing_store', label: 'Lojas de Roupas' },
  { key: 'electronics_store', label: 'Lojas de Eletrônicos' },
  { key: 'furniture_store', label: 'Lojas de Móveis' },
  { key: 'toy_store', label: 'Lojas de Brinquedos' },
  { key: 'sporting_goods_store', label: 'Lojas de Esportes' },
  { key: 'market', label: 'Mercados' },
  { key: 'pharmacy', label: 'Farmácias' },
  { key: 'gas_station', label: 'Postos de Gasolina' },
  { key: 'bank', label: 'Agências Bancárias' },
  { key: 'beauty_salon', label: 'Salões de Beleza' },
  { key: 'car_repair', label: 'Oficinas Mecânicas' },
  { key: 'laundry', label: 'Lavanderias' },
  { key: 'post_office', label: 'Correios' },
  { key: 'park', label: 'Parques' },
  { key: 'museum', label: 'Museus' },
  { key: 'theater', label: 'Teatros' },
  { key: 'cinema', label: 'Cinemas' },
  { key: 'gym', label: 'Academias' },
  { key: 'convention_center', label: 'Centros de Convenções' },
  { key: 'night_club', label: 'Boates' },
  { key: 'hospital', label: 'Hospitais' },
  { key: 'clinic', label: 'Clínicas' },
  { key: 'doctor', label: 'Consultórios Médicos' },
  { key: 'dentist', label: 'Dentistas' },
  { key: 'laboratory', label: 'Laboratórios' },
  { key: 'manipulation_pharmacy', label: 'Farmácias de Manipulação' },
  { key: 'bus_station', label: 'Estações de Ônibus' },
  { key: 'metro_station', label: 'Estações de Metrô' },
  { key: 'airport', label: 'Aeroportos' },
  { key: 'bus_terminal', label: 'Terminais Rodoviários' },
  { key: 'parking', label: 'Estacionamentos' },
  { key: 'school', label: 'Escolas' },
  { key: 'college', label: 'Faculdades' },
  { key: 'language_school', label: 'Cursos de Idiomas' },
  { key: 'library', label: 'Bibliotecas' },
  { key: 'hotel', label: 'Hotéis' },
  { key: 'inn', label: 'Pousadas' },
  { key: 'tourist_attraction', label: 'Atrações Turísticas' },
  { key: 'travel_agency', label: 'Agências de Viagem' },
  { key: 'real_estate_agency', label: 'Imobiliárias' },
  { key: 'hardware_store', label: 'Lojas de Materiais de Construção' },
  { key: 'construction_company', label: 'Construtoras' },
  { key: 'computer_store', label: 'Lojas de Informática' },
  { key: 'repair_shop', label: 'Assistências Técnicas' },
  { key: 'cyber_cafe', label: 'Cyber Cafés' },
  ];
  